#
# This source file is part of the CardinalKit open-source project
#
# SPDX-FileCopyrightText: 2022 CardinalKit and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test Swift Package using Xcodebuild

on:
  workflow_call:
    inputs:
      path:
        description: 'The path where the Swift Package is located. Defaults to $GITHUB_WORKSPACE'
        required: false
        type: string
        default: '.'
      packagename:
        description: 'Name of the package passed to Xcode on macOS builds. Required for generating a test coverage or testing the DoC documentation generation'
        required: true
        type: string

jobs:
  build_and_test:
    name: Build and Test Swift Package
    runs-on: macos-12
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Check Environment
      run: |
          xcodebuild -version
          swift --version
          echo "inputs.packagename: ${{ inputs.packagename }}"
          echo "inputs.path: ${{ inputs.path }}"
    - name: Build and Test
      run: |
          xcodebuild test \
            -scheme ${{ inputs.packagename }}-Package \
            -sdk iphonesimulator \
            -destination "name=iPhone 14 Pro Max" \
            -enableCodeCoverage YES \
            -resultBundlePath ${{ inputs.packagename }}.xcresult \
            CODE_SIGNING_ALLOWED="NO"
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.packagename }}.xcresult
        path: ${{ inputs.packagename }}.xcresult
